apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
rules:
  - apiGroups:
      - "prefixrouter.app"
    resources:
      - routes
    verbs:
      - get
      - list
      - list-watch
      - watch
