apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        "consul.hashicorp.com/connect-service": "{{ .Values.name }}"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/connect-service-upstreams": "{{ .Values.name }}:8081"
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: "ingress-router-controller"
          image: "{{ .Values.controller.repository }}:{{ .Values.controller.tag }}"
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          env:
            - name: DC
              value: {{ .Values.dc }}
            - name: ROUTER_SERVICE_NAME
              value: "{{ .Values.name }}"
        - name: default-response
          image: "envoyproxy/envoy:latest"
          ports:
            - name: http
              containerPort: 8082
          command:
            - "sh"
            - "-c"
            - |
              cat >/etc/envoy/envoy.yaml <<EOF
              static_resources:
                listeners:
                  - address:
                      socket_address:
                        address: 0.0.0.0
                        port_value: 8080
                    filter_chains:
                      - filters:
                          - name: envoy.http_connection_manager
                            typed_config:
                              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                              stat_prefix: default-service
                              http_filters:
                                - name: envoy.router
                                  config: {}
                              route_config:
                                name: local_route
                                virtual_hosts:
                                  - name: local_service,
                                    domains: ["*"]
                                    routes:
                                      - match:
                                          prefix: "/"
                                        direct_response:
                                          status: 200
                                          body:
                                            inline_string: "Missing page"
                  - address:
                      socket_address:
                        address: 0.0.0.0
                        port_value: 8082
                    filter_chains:
                      - filters:
                          - name: envoy.http_connection_manager
                            typed_config:
                              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                              stat_prefix: inbound
                              http_filters:
                                - name: envoy.router
                                  config: {}
                              route_config:
                                name: route
                                virtual_hosts:
                                  - name: service,
                                    domains: ["*"]
                                    routes:
                                      - match: { prefix: "/" }
                                        route:
                                          cluster: inbound-localhost
                clusters:
                  - name: inbound-localhost
                    connect_timeout: 0.25s
                    type: STATIC
                    load_assignment:
                      cluster_name: inbound-localhost
                      endpoints:
                        lb_endpoints:
                          endpoint:
                            address:
                              socket_address: { address: 127.0.0.1, port_value: 8081 }
              EOF
              envoy -c /etc/envoy/envoy.yaml --base-id 1
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
