# Default values for service-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: "service"

image:
  repository: service
  tag: v1

service:
  type: ClusterIP
  port: 8080

upstreams: "svc1:3333,svc2:3334,svc3:3335,svc4:3336"
